# Generated by Django 2.0.13 on 2019-09-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.RemoveField(
            model_name='events',
            name='created',
        ),
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.CharField(default='surya', max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
