# Generated by Django 2.0.13 on 2019-09-09 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0003_auto_20190909_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='id',
        ),
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.IntegerField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='events',
            name='start_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Event Date'),
        ),
    ]
