# Generated by Django 2.0.13 on 2019-09-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0004_auto_20190909_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
