# Generated by Django 2.0.13 on 2019-09-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0005_auto_20190909_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(default='general', max_length=255),
        ),
    ]
