# Generated by Django 2.0.13 on 2019-09-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0007_auto_20190913_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_state',
            field=models.IntegerField(blank=True),
        ),
    ]
