# Generated by Django 2.0.13 on 2019-09-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0008_auto_20190913_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_state',
            field=models.BooleanField(default=True),
        ),
    ]
