# Generated by Django 2.0.13 on 2019-09-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0009_auto_20190913_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='photos_link',
            field=models.CharField(default='photos', max_length=255, null=True),
        ),
    ]
