# Generated by Django 2.0.13 on 2019-09-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0010_events_photos_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='photos_link',
            field=models.CharField(default='photos', max_length=255),
        ),
    ]
