# Generated by Django 2.0.13 on 2019-09-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0011_auto_20190913_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='medium_link',
            field=models.CharField(default='meduim', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='registration_link',
            field=models.CharField(default='registeration', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='photos_link',
            field=models.CharField(default='photos', max_length=255, null=True),
        ),
    ]
